/*
 * managerView.java
 */
package orbit;

import java.awt.Dimension;
import javax.swing.*;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;

// vijava
import java.net.URL;
import com.vmware.vim25.*;
import com.vmware.vim25.mo.*;
import java.net.MalformedURLException;

/**
 * The application's main frame.
 */
public class managerLogin extends FrameView {

    private SingleFrameApplication Application;

    public managerLogin(SingleFrameApplication app) {
        super(app);

        initComponents();

        // set form size
        this.getFrame().setResizable(false);
        this.getFrame().setPreferredSize(new Dimension(350, 150));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        loginButton = new javax.swing.JButton();
        serverLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        serverTestField = new javax.swing.JTextField();
        loginTextField = new javax.swing.JTextField();
        passwordPasswordField = new javax.swing.JPasswordField();

        loginPanel.setName("loginPanel"); // NOI18N
        loginPanel.setPreferredSize(new java.awt.Dimension(350, 250));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(orbit.manager.class).getContext().getResourceMap(managerLogin.class);
        loginButton.setText(resourceMap.getString("loginButton.text")); // NOI18N
        loginButton.setName("loginButton"); // NOI18N
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginAction(evt);
            }
        });

        serverLabel.setLabelFor(serverTestField);
        serverLabel.setText(resourceMap.getString("serverLabel.text")); // NOI18N
        serverLabel.setName("serverLabel"); // NOI18N

        loginLabel.setLabelFor(loginTextField);
        loginLabel.setText(resourceMap.getString("loginLabel.text")); // NOI18N
        loginLabel.setName("loginLabel"); // NOI18N

        passwordLabel.setLabelFor(passwordPasswordField);
        passwordLabel.setText(resourceMap.getString("passwordLabel.text")); // NOI18N
        passwordLabel.setName("passwordLabel"); // NOI18N

        serverTestField.setName("serverTestField"); // NOI18N

        loginTextField.setText(resourceMap.getString("loginTextField.text")); // NOI18N
        loginTextField.setName("loginTextField"); // NOI18N

        passwordPasswordField.setName("passwordPasswordField"); // NOI18N

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginButton)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordLabel)
                            .addComponent(serverLabel)
                            .addComponent(loginLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordPasswordField)
                            .addComponent(loginTextField)
                            .addComponent(serverTestField, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serverLabel)
                    .addComponent(serverTestField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginLabel)
                    .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginButton)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        setComponent(loginPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void loginAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginAction
        // locals
        URL urlServer = null;
        String stringUser, stringPassword;
        ServiceInstance si = null;
        boolean valid = true;

        // validate
        if (!serverTestField.getText().isEmpty()) {
            try {
                if (serverTestField.getText().endsWith("/sdk")) { // allow for full url entry
                    urlServer = new URL(serverTestField.getText());
                } else {
                    urlServer = new URL("https://" + serverTestField.getText() + "/sdk");
                }
            } catch (MalformedURLException e) {
                JOptionPane.showMessageDialog(null, "Invalid server!", "Error", JOptionPane.ERROR_MESSAGE);
                valid = false;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please enter a server!", "Warning", JOptionPane.WARNING_MESSAGE);
            valid = false;
        }

        stringUser = loginTextField.getText();
        if (valid && stringUser.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a login!", "Warning", JOptionPane.WARNING_MESSAGE);
            valid = false;
        }

        stringPassword = new String(passwordPasswordField.getPassword());
        if (valid && stringPassword.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a password!", "Warning", JOptionPane.WARNING_MESSAGE);
            valid = false;
        }

        // connect
        if (valid) {
            try {
            si = new ServiceInstance(urlServer, stringUser, stringPassword, true);
            } catch (com.vmware.vim25.InvalidLogin il) {
                JOptionPane.showMessageDialog(null, "Invalid login!", "Warning", JOptionPane.WARNING_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

        if (si != null) {
            Application.show(new managerView(Application, si));
        }

    }//GEN-LAST:event_loginAction
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordPasswordField;
    private javax.swing.JLabel serverLabel;
    private javax.swing.JTextField serverTestField;
    // End of variables declaration//GEN-END:variables
}
